# Generated by Django 5.1.7 on 2025-12-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoNinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('num_ninos_actual', models.IntegerField(default=0)),
                ('capacidad_maxima', models.IntegerField()),
                ('descripcion_actividades', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos de Niños',
            },
        ),
        migrations.CreateModel(
            name='PadreMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20)),
                ('relacion_con_nino', models.CharField(max_length=50)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGuarderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dni', models.CharField(max_length=20)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Personal de Guardería',
            },
        ),
        migrations.CreateModel(
            name='ActividadGuarderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('material_requerido', models.TextField(blank=True, null=True)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_Guarderia.gruponinos')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('necesidades_especiales', models.TextField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField()),
                ('grupo_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninos', to='app_Guarderia.gruponinos')),
                ('padre_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='app_Guarderia.padremadre')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('mes_correspondiente', models.DateField()),
                ('estado_pago', models.CharField(default='Pagado', max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_Guarderia.nino')),
            ],
            options={
                'verbose_name_plural': 'Pagos Mensualidades',
            },
        ),
        migrations.AddField(
            model_name='gruponinos',
            name='personal_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='app_Guarderia.personalguarderia'),
        ),
        migrations.CreateModel(
            name='AsistenciaNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estuvo_enfermo', models.BooleanField(default=False)),
                ('notas_dia', models.TextField(blank=True, null=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app_Guarderia.nino')),
                ('personal_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Guarderia.personalguarderia')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
